languageCode = "en"
languageName = "English"
weight = 1
title = "The Total Token Vortex"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "The Total Token Vortex"

[params.author]
  name = "Maciej Kalisiak"
  headline = "Quantum hallucinations, delivered at scale."
  image = "img/profile.jpg"
  links = [
    { email = "mailto:mkalisiak@gmail.com" },
    { github = "https://github.com/maciekk" },
    { linkedin = "https://www.linkedin.com/in/maciejkalisiak" },
    { "smugmug-icon" = "https://m4c1ek.smugmug.com" },
  ]
