languageCode = "en"
languageName = "English"
weight = 1
title = "The Total Token Vortex"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "The Total Token Vortex"

[params.author]
  name = "Maciej Kalisiak"
  image = "img/profile.jpg"
