# -- Main Menu --
[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 30

[[main]]
  name = "About"
  pageRef = "about"
  weight = 40

[[main]]
  name = "CV"
  pageRef = "cv"
  weight = 50

# -- Footer Menu --
