# -- Main Menu --
[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "CV"
  url = "/cv.pdf"
  weight = 30

# -- Footer Menu --
