colorScheme = "neon"
subtitle = "Mostly Artless. Entirely Improbable. Vogon Poetry-esque."
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true

mainSections = ["posts"]

disableImageOptimization = false
hotlinkFeatureImage = true
disableTextInHeader = false

highlightCurrentMenuArea = false
smartTOC = true
smartTOCHideUnfocusedChildren = false

fingerprintAlgorithm = "sha512"

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "hero"
  homepageImage = "img/hero-bg.png"
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "posts"
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showDraftLabel = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = false
  relatedContentLimit = 3
  showTaxonomies = true
  showWordCount = true
  sharingLinks = ["reddit", "bluesky", "email"]
  showZenMode = false
  showEdit = true
  editURL = "https://github.com/maciekk/total-token-vortex/edit/master/content/"
  editAppendPath = true

[list]
  showHero = false
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = false
  showCards = true
  orderByWeight = false
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = false
  showBreadcrumbs = true
  showTableOfContents = false
  cardView = false

[term]
  showHero = false
  showBreadcrumbs = true
  showTableOfContents = false
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false
